// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4OxM5-D1IvbpZlnPT2LmF4c4OwMlL8WM',
    appId: '1:356601250441:web:e792565b7a990b81babc58',
    messagingSenderId: '356601250441',
    projectId: 'flutterauth-d3356',
    authDomain: 'flutterauth-d3356.firebaseapp.com',
    storageBucket: 'flutterauth-d3356.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCUAGEecO8TXcurlj7ObwnZNtclecYrs',
    appId: '1:356601250441:android:bb890f1ea5a267d3babc58',
    messagingSenderId: '356601250441',
    projectId: 'flutterauth-d3356',
    storageBucket: 'flutterauth-d3356.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmzQjUMzQosiKKbqqbKyCMgqQqEezihU',
    appId: '1:356601250441:ios:4560ec44d034692fbabc58',
    messagingSenderId: '356601250441',
    projectId: 'flutterauth-d3356',
    storageBucket: 'flutterauth-d3356.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmzQjUMzQosiKKbqqbKyCMgqQqEezihU',
    appId: '1:356601250441:ios:c706636f825849ebbabc58',
    messagingSenderId: '356601250441',
    projectId: 'flutterauth-d3356',
    storageBucket: 'flutterauth-d3356.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
